==10008== Memcheck, a memory error detector for x86-linux.
==10008== Copyright (C) 2002-2005, and GNU GPL'd, by Julian Seward et al.
==10008== Using valgrind-2.4.0, a program supervision framework for x86-linux.
==10008== Copyright (C) 2000-2005, and GNU GPL'd, by Julian Seward et al.
==10008== For more details, rerun with: -v
==10008== 
created PathList @ 0x1ba194b0
created Path @ 0x1bde0838
created PathList @ 0x1bde0b48
created Path @ 0x1ba19740
created PathList @ 0x1bde0be8
created Path @ 0x1ba197e8
deleted Path @ 0x1ba197e8
deleted PathList @ 0x1bde0be8
created PathList @ 0x1bde0ed8
created Path @ 0x1ba19ae0
deleted Path @ 0x1ba19ae0
deleted PathList @ 0x1bde0ed8
deleted Path @ 0x1ba19740
deleted PathList @ 0x1bde0b48
==10008== Jump to the invalid address stated on the next line
==10008==    at 0x0: ???
==10008==    by 0xB99A74: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBB55EB: PyObject_GenericGetAttr (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBB4D13: PyObject_GetAttr (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE2C0C: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE697A: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE709D: PyEval_EvalCodeEx (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE7361: PyEval_EvalCode (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xC00816: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xC01941: PyRun_SimpleFileExFlags (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xC02993: PyRun_AnyFileExFlags (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xC0768D: Py_Main (in /usr/lib/libpython2.3.so.1.0)
==10008==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==10008== 
==10008== Process terminating with default action of signal 11 (SIGSEGV)
==10008==  Access not within mapped region at address 0x0
==10008==    at 0x0: ???
==10008==    by 0xB99A74: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBB55EB: PyObject_GenericGetAttr (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBB4D13: PyObject_GetAttr (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE2C0C: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE697A: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE709D: PyEval_EvalCodeEx (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE7361: PyEval_EvalCode (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xC00816: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xC01941: PyRun_SimpleFileExFlags (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xC02993: PyRun_AnyFileExFlags (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xC0768D: Py_Main (in /usr/lib/libpython2.3.so.1.0)
5.0990028172e-16
==10008== 
==10008== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 2621 from 7)
==10008== malloc/free: in use at exit: 1622357 bytes in 775 blocks.
==10008== malloc/free: 9317 allocs, 8542 frees, 6536369 bytes allocated.
==10008== For counts of detected errors, rerun with: -v
==10008== searching for pointers to 775 not-freed blocks.
==10008== checked 1953716 bytes.
==10008== 
==10008== 
==10008== 1316 bytes in 3 blocks are possibly lost in loss record 29 of 38
==10008==    at 0x1B904222: malloc (vg_replace_malloc.c:130)
==10008==    by 0xBB6768: PyObject_Malloc (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xC08C5D: _PyObject_GC_Malloc (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xC08D67: _PyObject_GC_NewVar (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBA17FE: PyFrame_New (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE6A72: PyEval_EvalCodeEx (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE7361: PyEval_EvalCode (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBF86DB: PyImport_ExecCodeModuleEx (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBF8B0C: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBF9D80: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBFA202: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBFA42E: (within /usr/lib/libpython2.3.so.1.0)
==10008== 
==10008== 
==10008== 7812 bytes in 18 blocks are possibly lost in loss record 35 of 38
==10008==    at 0x1B904C61: realloc (vg_replace_malloc.c:196)
==10008==    by 0xBB6C18: PyObject_Realloc (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xC08DBC: _PyObject_GC_Resize (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBA18B2: PyFrame_New (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE68E3: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE709D: PyEval_EvalCodeEx (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE5D8E: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE697A: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE709D: PyEval_EvalCodeEx (in /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE5D8E: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE697A: (within /usr/lib/libpython2.3.so.1.0)
==10008==    by 0xBE709D: PyEval_EvalCodeEx (in /usr/lib/libpython2.3.so.1.0)
==10008== 
==10008== LEAK SUMMARY:
==10008==    definitely lost: 0 bytes in 0 blocks.
==10008==      possibly lost: 9128 bytes in 21 blocks.
==10008==    still reachable: 1613229 bytes in 754 blocks.
==10008==         suppressed: 0 bytes in 0 blocks.
==10008== Reachable blocks (those to which a pointer was found) are not shown.
==10008== To see them, rerun with: --show-reachable=yes
